import type {
  DashboardSummary,
  DirectoryPage,
  EvidencePage,
  IncidentQueue,
  IncidentTimeline,
  Investigation,
  InventoryItem,
  NodeItem,
  PodItem,
  RemediationPage,
  ResourceDetail,
  ServiceItem,
  TimelineEventDetail,
} from "./types";

export const MOCK_INCIDENT_ID = "inc-4082";
export const MOCK_EVENT_ID = "evt-config-change";
export const MOCK_RESOURCE_ID = "postgresql-primary";

export const mockDashboard: DashboardSummary = {
  greetingName: "Zick",
  counts: { nodes: 12, pods: 84, deployments: 24, services: 18, namespaces: 3 },
  health: {
    critical: 20,
    high: 30,
    medium: 10,
    low: 40,
    healthyPercent: 64.24,
    label: "Healthy",
  },
  performance: {
    mttdMinutes: 2.4,
    mttrMinutes: 47,
    rcaMinutes: 47,
    series: [
      { time: "10:00", cpu: 42, ram: 65 },
      { time: "11:00", cpu: 55, ram: 68 },
      { time: "12:00", cpu: 48, ram: 72 },
      { time: "13:00", cpu: 67, ram: 78 },
      { time: "14:00", cpu: 73, ram: 81 },
      { time: "15:00", cpu: 61, ram: 76 },
    ],
  },
  recentIncidents: [
    { id: MOCK_INCIDENT_ID, title: "Spiking storage usage", service: "payment-service", severity: "Critical" },
    { id: "inc-4081", title: "Checkout latency", service: "checkout-svc", severity: "High" },
    { id: "inc-4079", title: "Replica lag", service: "postgresql-primary", severity: "Critical" },
    { id: "inc-4074", title: "Ingress 5xx burst", service: "nginx-ingress", severity: "Low" },
  ],
  activeInvestigations: 2,
};

export const mockIncidentQueue: IncidentQueue = {
  workers: ["worker-01", "worker-02"],
  selectedWorker: "worker-01",
  kind: "pods",
  activeCount: 2,
  incidents: [
    {
      id: MOCK_INCIDENT_ID,
      code: "INC-4082",
      title: "Storage & DB Conn Failure",
      namespace: "production-db",
      rootCauseLabel: "postgresql-primary (Root Cause)",
      severity: "Critical",
      status: "In Progress",
      isActive: true,
      summary: "High error rate",
      occurredAgo: "4 mins ago",
      metrics: { cpu: 92, memory: 89, restarts: 6, confidence: 85 },
      workflowStatus: "In Progress",
    },
    {
      id: "inc-4081",
      code: "INC-4081",
      title: "Checkout latency",
      namespace: "production-api",
      rootCauseLabel: "api-server",
      severity: "High",
      status: "Open",
      isActive: false,
      summary: "P95 latency above SLO",
      occurredAgo: "18 mins ago",
      metrics: { cpu: 71, memory: 64, restarts: 1, confidence: 72 },
      workflowStatus: "Open",
    },
    {
      id: "inc-4074",
      code: "INC-4074",
      title: "Ingress 5xx burst",
      namespace: "ingress-nginx",
      rootCauseLabel: "nginx-ingress",
      severity: "Low",
      status: "Resolved",
      isActive: false,
      summary: "Transient 5xx",
      occurredAgo: "2 hours ago",
      metrics: { cpu: 31, memory: 54, restarts: 0, confidence: 61 },
      workflowStatus: "Resolved",
    },
  ],
  preview: {
    name: "order-svc-4082",
    namespace: "default",
    node: "worker-01",
    createdAt: "May 16, 2025 10:24:17",
    isActive: true,
  },
};

const incidentDetail = {
  id: MOCK_INCIDENT_ID,
  code: "INC-4082",
  title: "Storage & DB Conn Failure",
  status: "Recovered" as const,
  severity: "Critical" as const,
  duration: "23m 14s",
  startTime: "Aug 22, 2026 15:15:08",
  endTime: "Aug 22, 2026 15:41:56",
  affectedService: "pymt-svc",
  environment: "production",
  owner: "xyz-team",
  sinceLabel: "Since 15:18 (32m)",
};

export const mockIncidentTimeline: IncidentTimeline = {
  incident: incidentDetail,
  events: [
    {
      id: MOCK_EVENT_ID,
      time: "15:15:08",
      title: "Deployment / Config Change",
      description: ["Connection pool size changed", "From 50→75 in pymt-svc"],
      color: "#FF0000",
      details: [
        { label: "Change by", value: "Jane Doe" },
        { label: "Type", value: "Config Change" },
        { label: "Resource", value: "config/checkout-db.yaml" },
      ],
    },
    {
      id: "evt-first-anomaly",
      time: "15:18:42",
      title: "First Anomaly Detected",
      description: ["PostgreSQL timeout errors increased", "Error rate raised to 2.3% (threshold: 1%)"],
      color: "#F1272D",
      details: [
        { label: "Metric", value: "postgresql.timeout" },
        { label: "Value", value: "2.3%" },
        { label: "Threshold", value: ">1%" },
      ],
    },
    {
      id: "evt-downstream",
      time: "15:19:02",
      title: "Downstream Anomalies",
      description: ["Payment latency increased", "3 Pods affected, error rate 2.8%"],
      color: "#F45B1B",
      details: [
        { label: "Affected Pods", value: "3" },
        { label: "Latency", value: "3.6s (259%)" },
        { label: "Error Rate", value: "2.8%" },
      ],
    },
    {
      id: "evt-detected",
      time: "15:19:27",
      title: "Incident Detected",
      description: ["AKAR detected an incident and", "created INC-4082"],
      color: "#F39A18",
      details: [
        { label: "Severity", value: "Critical", valueColor: "text-red-500" },
        { label: "Impact", value: "High" },
        { label: "Status", value: "Open" },
      ],
    },
    {
      id: "evt-rca",
      time: "15:27:13",
      title: "RCA Identified",
      description: ["PostgreSQL connection pool exhaustion", "confidence 94%"],
      color: "#F2C318",
      details: [
        { label: "Root Cause", value: "Connection pool exhaustion" },
        { label: "Confidence", value: "94%" },
        { label: "Signals", value: "4 supporting, 1 contradicting" },
      ],
    },
    {
      id: "evt-remediation",
      time: "15:30:02",
      title: "Remediation Executed",
      description: ["Rollback config change", "Connection pool size reverted to 50"],
      color: "#E9EE13",
      details: [
        { label: "Action", value: "rollback configuration" },
        { label: "By", value: "John Doe" },
        { label: "Status", value: "Success", valueColor: "text-green-600" },
      ],
    },
    {
      id: "evt-recovered",
      time: "15:41:56",
      title: "Service Recovered",
      description: ["Rollback config change", "Connection pool size reverted to 50"],
      color: "#36E51F",
      details: [
        { label: "Error Rate", value: "0%" },
        { label: "Latency", value: "240ms" },
        { label: "Status", value: "Recovered", valueColor: "text-green-600" },
      ],
    },
  ],
};

export const mockTimelineEventDetail: TimelineEventDetail = {
  event: mockIncidentTimeline.events[0],
  incident: {
    ...incidentDetail,
    title: "Storage & DB Conn Failure",
  },
  windowLabel: "May 22, 2026 15:15 - 15:41 (26m 14s)",
  changeBy: "Jane Doe",
  type: "Config Change",
  resource: "config/checkout-db.yaml",
  changeId: "CFG-93217",
  leadTimeLabel: "3m 34s before first anomaly detected",
  summary: "Connection pool size changed from 50 → 70 in pymt-svc deployment",
  configDiff: {
    file: "config/checkout-db.yaml",
    lines: [
      { number: "12", text: "database:", kind: "key" },
      { number: "13", text: "host: postgres-primary.checkout.svc.cluster.local", kind: "normal" },
      { number: "14", text: "port: 5432", kind: "normal" },
      { number: "15", text: "pool:", kind: "key" },
      { number: "16", text: "maxOpenConns: 75", kind: "removed" },
      { number: "17", text: "maxIdleConns: 20", kind: "added" },
      { number: "18", text: "connMaxLifetime: 30m", kind: "normal" },
    ],
  },
  signals: [
    { title: "Database Connections (active)", value: "56", suffix: "connections", type: "database", sparkline: [18, 22, 20, 28, 24, 35, 48, 44, 70, 58, 82, 56, 60, 58, 72, 80, 64, 74, 60, 80] },
    { title: "Checkout Error Rate", value: "0.2%", suffix: "", type: "error", sparkline: [18, 20, 19, 30, 22, 38, 50, 44, 72, 68, 58, 78, 55, 74, 52, 55, 62, 52, 62, 78] },
  ],
  aiImpact: {
    headline: "This change increased the database connection pool size",
    body: "Higher pool size may increase database load and connection if not matched with database capacity",
    riskLevel: "Medium",
    potentialImpact: "Performance Degradation",
    likelihood: "Possible (42%)",
    whyItMatters: "Increasing the connection pool may lead to connection exhaustion, timeouts and cascading failures if the database cannot handle the additional connections",
  },
  relatedEvents: [
    {
      id: "evt-first-anomaly",
      time: "15:18:42",
      title: "First Anomaly Detected",
      color: "red",
      description: "PostgreSQL timeout errors increased\nError rate raised to 2.3% (threshold: 1%)",
      metric: "postgresql.timeout",
    },
    {
      id: "evt-downstream",
      time: "15:19:02",
      title: "Downstream Anomalies",
      color: "orange",
      description: "Payment latency increased\n3 Pods affected, error rate 2.8%",
      metric: "3",
      metricLabel: "Affected Pods",
    },
  ],
  correlationNote:
    "This change occurred 3m 34s before the first anomaly and is correlated with the incidents AKAR identified it as a potential contributing factor",
};

export const mockInvestigation: Investigation = {
  incident: {
    ...incidentDetail,
    title: "PostgreSQL Connection Timeout Errors",
    status: "Open",
    endTime: null,
  },
  rootCause: {
    prediction: "PostgreSQL connection pool exhaustion",
    confidence: 94,
  },
  impact: {
    description: "3 services, 2 pods, 1 datastore",
    percent: 95,
    label: "Critical",
  },
  userImpact: {
    description: "Payment failures -2.3% requests failed",
    percent: 80,
    label: "Critical",
  },
  mttr: { value: "12m", label: "Ongoing", target: "Target <30m" },
  rcaDetection: { value: "4m 14s", label: "Current", target: "Target <5m" },
  topology: {
    nodes: [
      { id: "web", title: "Web App", status: "Healthy", kind: "web", critical: false, position: { left: "18.5%", top: "5%", width: "23%" } },
      { id: "gateway", title: "API Gtw", status: "Healthy", kind: "gateway", critical: false, position: { left: "3%", top: "47%", width: "20%" } },
      { id: "payment", title: "Payment Service", status: "Critical", subtitle: "12 pods affected", kind: "service", critical: true, position: { left: "33%", top: "43%", width: "28%" } },
      { id: "pg-primary", title: "PostgreSQL primary", status: "Critical", subtitle: "Connection pod exhausted", kind: "db", critical: true, position: { left: "66%", top: "5%", width: "30%" } },
      { id: "pg-replica", title: "PostgreSQL replica", status: "Healthy", kind: "db", critical: false, position: { left: "68.5%", top: "78%", width: "30%" } },
    ],
    edges: [
      { from: "web", to: "payment", critical: false, path: "M 415 47 L 475 47 L 475 123" },
      { from: "gateway", to: "payment", critical: false, path: "M 230 158 L 330 158" },
      { from: "payment", to: "pg-primary", critical: true, path: "M 540 128 C 525 100, 645 50, 650 48" },
      { from: "payment", to: "pg-replica", critical: false, path: "M 510 160 C 530 220, 560 245, 685 250" },
    ],
  },
  analysisReasons: [
    "Connection pool utilization > 95% for 4m",
    "Spike in connection timeout errors (2.3k/min)",
    "Checkout service errors correlated (r = 0.92)",
    "Started right after pool size change (50 → 75)",
    "No abnormality in network, CPU, or memory",
  ],
  alternatives: [
    { label: "Database slow query", value: "18%" },
    { label: "Network latency to DB", value: "8%" },
    { label: "Pod resource exhaustion", value: "5%" },
  ],
  evidence: [
    { id: "ev-1", time: "15:24:10", ago: "4 mins ago", title: "Database Connection Errors Spiked", type: "Metric", relevance: "98%", source: "Prometheus", component: "postgresql-primary", sparkline: [20, 24, 18, 32, 26, 40, 52, 48, 78, 62, 82, 55, 58, 54, 68, 78], sparklineColor: "red" },
    { id: "ev-2", time: "15:24:05", ago: "4 mins ago", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%", source: "app-logs", component: "pymt-svc" },
    { id: "ev-3", time: "15:23:58", ago: "5 mins ago", title: "Database Response Time Increased", type: "Metric", relevance: "90%", source: "Prometheus", component: "postgresql-primary", sparkline: [20, 22, 22, 28, 34, 42, 50, 46, 74, 58, 76, 52, 55, 42, 32, 36], sparklineColor: "orange" },
  ],
  recommendedAction: {
    id: "act-increase-pool",
    title: "Increase connection pool size",
    description: "Increase PostgreSQL connection pool size to 100 or rollback to previous configuration.",
    expectedImpact: "Restore connections and reduce timeout errors",
    confidence: "High (91%)",
    riskLevel: "Medium",
    manualOnly: true,
  },
};

const directoryCounts = { inventory: 114, pods: 84, services: 18, nodes: 12, deployments: 24, namespaces: 3 };

export const mockInventory: DirectoryPage<InventoryItem> = {
  counts: directoryCounts,
  highlights: [
    { title: "Kubernetes Nodes", value: "12", description: "12/12 Ready", tone: "ok" },
    { title: "Running Pods", value: "84", description: "2 Anomalous", tone: "critical" },
    { title: "Microservices", value: "18", description: "4 Degraded", tone: "warning" },
    { title: "Namespaces", value: "6", description: "production, staging...", tone: "neutral" },
  ],
  items: [
    { id: MOCK_RESOURCE_ID, name: "postgresql-primary-0", description: "Port: 8080/TCP", type: "StatefulSet Pod", namespace: "production-db", cpuRam: "42% / 99.8%", status: "Critical" },
    { id: "redis-cache", name: "redis-cache-0", description: "Port: 6379/TCP", type: "StatefulSet Pod", namespace: "production-cache", cpuRam: "78% / 91.4%", status: "High" },
    { id: "nginx-ingress", name: "nginx-ingress-controller", description: "Port: 443/TCP", type: "Deployment Pod", namespace: "ingress-nginx", cpuRam: "31% / 64.2%", status: "Low" },
    { id: "api-server", name: "api-server-7d9f8c6b5", description: "Port: 8080/TCP", type: "Deployment Pod", namespace: "production-api", cpuRam: "86% / 94.7%", status: "Critical" },
    { id: "worker-node-01", name: "worker-node-01", description: "Port: 9090/TCP", type: "DaemonSet Pod", namespace: "production-worker", cpuRam: "67% / 82.3%", status: "High" },
    { id: "frontend-web", name: "frontend-web-5c8d7f9b", description: "Port: 3000/TCP", type: "Deployment Pod", namespace: "production-web", cpuRam: "24% / 51.6%", status: "Low" },
  ],
};

export const mockPods: DirectoryPage<PodItem> = {
  counts: directoryCounts,
  highlights: [
    { title: "Total Pods", value: "84", description: "across 6 namespaces", tone: "neutral" },
    { title: "Healthy Pods", value: "81", description: "96.4% Operational", tone: "ok" },
    { title: "Anomalous / Restart", value: "3", description: "Attention Required", tone: "critical" },
    { title: "Crash Loop Detected", value: "1", description: "xyz-service-pod-02", tone: "warning" },
  ],
  items: [
    { id: MOCK_RESOURCE_ID, name: "postgresql-primary-0", description: "Port: 5432/TCP", nodeHost: "worker-node-01", namespace: "production-db", restarts: 2, cpuRam: "42% / 78.4%", status: "Critical" },
    { id: "redis-cache", name: "redis-cache-0", description: "Port: 6379/TCP", nodeHost: "worker-node-02", namespace: "production-cache", restarts: 0, cpuRam: "68% / 82.1%", status: "High" },
    { id: "nginx-ingress", name: "nginx-ingress-7d9f8c6b5", description: "Port: 443/TCP", nodeHost: "worker-node-03", namespace: "ingress-nginx", restarts: 1, cpuRam: "31% / 54.6%", status: "Low" },
    { id: "api-server", name: "api-server-6f4d8c7b9", description: "Port: 8080/TCP", nodeHost: "worker-node-01", namespace: "production-api", restarts: 7, cpuRam: "89% / 93.7%", status: "Critical" },
  ],
};

export const mockServices: DirectoryPage<ServiceItem> = {
  counts: directoryCounts,
  highlights: [
    { title: "Total Services", value: "18", description: "ClusterIP & Ingress", tone: "neutral" },
    { title: "Normal Traffic", value: "15", description: "83.3% Nominal", tone: "ok" },
    { title: "Degraded / 5XX Spikes", value: "3", description: "Cascading Latency", tone: "critical" },
    { title: "Avg Services Latency", value: "180ms", description: "Spike (P95)", tone: "warning" },
  ],
  items: [
    { id: "pymt-svc", name: "pymt-svc", typeProtocol: "ClusterIP / TCP", namespace: "production-payment", targetPods: 12, latencyP95: "3.6s", status: "Critical" },
    { id: "checkout-svc", name: "checkout-svc", typeProtocol: "ClusterIP / TCP", namespace: "production-api", targetPods: 6, latencyP95: "420ms", status: "High" },
    { id: "web-svc", name: "web-svc", typeProtocol: "Ingress / HTTPS", namespace: "production-web", targetPods: 4, latencyP95: "84ms", status: "Low" },
  ],
};

export const mockNodes: DirectoryPage<NodeItem> = {
  counts: directoryCounts,
  highlights: [
    { title: "Total Nodes", value: "12", description: "12/12 Ready", tone: "ok" },
    { title: "Healthy Nodes", value: "10", description: "83.3% Nominal", tone: "ok" },
    { title: "Pressure / NotReady", value: "2", description: "Memory pressure", tone: "critical" },
    { title: "Avg Node CPU", value: "61%", description: "Cluster wide", tone: "warning" },
  ],
  items: [
    { id: "worker-node-01", hostname: "worker-node-01", role: "worker", versionOs: "v1.29 / Ubuntu 22.04", activePods: 18, cpuRam: "71% / 82%", status: "High" },
    { id: "worker-node-02", hostname: "worker-node-02", role: "worker", versionOs: "v1.29 / Ubuntu 22.04", activePods: 14, cpuRam: "42% / 99%", status: "Critical" },
    { id: "control-plane-01", hostname: "control-plane-01", role: "control-plane", versionOs: "v1.29 / Ubuntu 22.04", activePods: 8, cpuRam: "24% / 41%", status: "Low" },
  ],
};

export const mockResourceDetail: ResourceDetail = {
  id: MOCK_RESOURCE_ID,
  name: "postgresql-primary (StatefulSet DB)",
  namespace: "production-db",
  cluster: "k8s-prod-01",
  nodeHost: "worker-node-02",
  ip: "10.244.2.18",
  image: "postgres:15.3-alpine",
  uptime: "14d 6h",
  linkedIncident: { id: MOCK_INCIDENT_ID, code: "INC-4082", label: "Root Cause" },
  window: "Last 30m",
  metrics: [
    { id: "connections", title: "Active Connections vs Max Limit", centerText: "Max Limit: 100 conns", status: "99.8% (Exhausted)", tone: "critical", color: "#FF3B3B", sparkline: [12, 14, 15, 16, 18, 22, 40, 78, 96, 99] },
    { id: "cpu-ram", title: "CPU Usage & Memory Allocation", status: "CPU 42% • RAM 68%", tone: "ok", color: "#2D9B81", sparkline: [48, 50, 52, 51, 55, 53, 58, 56, 62, 64] },
    { id: "disk", title: "Disk Read/Write Latency (ms)", status: "Avg. 3.4ms", tone: "muted", color: "#6E42D5", sparkline: [40, 40, 41, 42, 38, 32, 48, 36, 60, 44] },
  ],
  logs: [
    { time: "14:07:20", level: "info", message: "LOG: database system is ready" },
    { time: "14:07:22", level: "error", message: "FATAL: remaining connection slots are reserved for non-superuser connections" },
    { time: "14:07:24", level: "warn", message: "pg_stat_activity: active=99, idle=1" },
    { time: "14:07:26", level: "error", message: "ERROR: conn pool rejected client" },
    { time: "14:07:29", level: "debug", message: "otel-collector: metric pushed" },
    { time: "14:07:35", level: "warn", message: "healthcheck probe failed: 500 error" },
  ],
  traces: [
    { id: "8f21bc90a", name: "POST /checkout", duration: "4,821ms", status: "504 Timeout", ok: false },
    { id: "2a77cc01d", name: "GET /inventory", duration: "34ms", status: "200 OK", ok: true },
  ],
};

const connErrorSeries = [
  { time: "15:00", value: 22 },
  { time: "15:05", value: 24 },
  { time: "15:10", value: 28 },
  { time: "15:15", value: 34 },
  { time: "15:20", value: 48 },
  { time: "15:22", value: 92 },
  { time: "15:24", value: 168 },
  { time: "15:25", value: 196 },
  { time: "15:26", value: 154 },
  { time: "15:30", value: 88 },
  { time: "15:35", value: 62 },
  { time: "15:40", value: 48 },
  { time: "15:45", value: 40 },
  { time: "15:50", value: 34 },
  { time: "15:55", value: 30 },
  { time: "16:00", value: 28 },
];

const timeoutLogSamples = [
  { time: "2026-08-01 13:25:42", level: "ERROR" as const, service: "payment-svc", message: "PSQLException: FATAL: remaining connection slots are reserved" },
  { time: "2026-08-01 13:25:45", level: "ERROR" as const, service: "payment-svc", message: "Connection to postgresql-primary timed out after 5000ms" },
  { time: "2026-08-01 13:25:48", level: "WARN" as const, service: "payment-svc", message: "Retrying database connection (attempt 3/5)" },
  { time: "2026-08-01 13:26:01", level: "ERROR" as const, service: "payment-svc", message: "Connection pool exhausted — rejecting incoming request" },
];

const timeoutPatterns = [
  { pattern: "DB_CONNECTION_TIMEOUT", description: "Database connection attempts timed out", occurrences: 142, severity: "Critical" as const },
  { pattern: "CONNECTION_POOL_EXHAUSTED", description: "Connection pool reached maximum limit", occurrences: 87, severity: "High" as const },
  { pattern: "RETRY_CONNECTION_FAILED", description: "All retry attempts to connect failed", occurrences: 64, severity: "High" as const },
  { pattern: "DB_REQUEST_TIMEOUT", description: "Database request execution timed out", occurrences: 39, severity: "Medium" as const },
];

export const mockEvidence: EvidencePage = {
  highlights: [
    { title: "All Evidence", value: "12", description: "Signals in window", tone: "neutral" },
    { title: "Metrics", value: "5", description: "Prometheus / OTel", tone: "warning" },
    { title: "Logs", value: "4", description: "Error bursts", tone: "critical" },
    { title: "Traces", value: "3", description: "Slow / failed spans", tone: "ok" },
  ],
  incident: {
    id: MOCK_INCIDENT_ID,
    code: "INC-4082",
    title: "Storage & DB Connection Failure",
    severity: "Critical",
    detectedAgo: "4 mins ago",
    activeFor: "15m 42s",
  },
  items: [
    {
      id: "ev-1",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:24:10",
      ago: "4 mins ago",
      title: "Database Connection Errors Spiked",
      type: "Metric",
      relevance: "98%",
      source: "Prometheus",
      component: "postgresql-primary",
      sparkline: [20, 24, 18, 32, 26, 40, 52, 48, 78, 62, 82, 55, 58, 54, 68, 78],
      sparklineColor: "red",
      description: "The spike in connection errors aligns with the incident start time and",
      descriptionAccent: "indicates the database is unable to handle incoming connections.",
      windowLabel: "Aug 01, 15:25 - 16:00",
      aiSummary: "the metric shows a strong correlation with the root cause",
      metricSeries: connErrorSeries,
      related: [
        { id: "ev-2", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%" },
        { id: "ev-5", title: "Slow Query Trace", type: "Trace", relevance: "90%" },
      ],
    },
    {
      id: "ev-2",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:24:05",
      ago: "4 mins ago",
      title: "PostgreSQL Connection Timeout Errors",
      type: "Log",
      relevance: "95%",
      source: "app-logs",
      component: "pymt-svc",
      description: "A significant increased in database connection errors detected",
      windowLabel: "Aug 01, 13:25 - 14:00",
      aiSummary: "the metric shows a strong correlation with the root cause",
      logSamples: timeoutLogSamples,
      patterns: timeoutPatterns,
      rawData: timeoutLogSamples
        .map((line) => `[${line.time}] ${line.level.padEnd(5)} ${line.service}: ${line.message}`)
        .join("\n"),
      affectedServices: [
        { name: "payment-svc", impact: "Checkout failures / 504" },
        { name: "checkout-svc", impact: "Elevated P95 latency" },
      ],
      related: [
        { id: "ev-1", title: "Database Connection Errors Spiked", type: "Metric", relevance: "98%" },
        { id: "ev-7", title: "Connection Pool Exhausted", type: "Log", relevance: "80%" },
      ],
    },
    {
      id: "ev-3",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:23:58",
      ago: "5 mins ago",
      title: "Database Response Time Increased",
      type: "Metric",
      relevance: "90%",
      source: "Prometheus",
      component: "postgresql-primary",
      sparkline: [20, 22, 22, 28, 34, 42, 50, 46, 74, 58, 76, 52, 55, 42, 32, 36],
      sparklineColor: "orange",
      description: "Query latency rose in lockstep with connection errors on the primary.",
      windowLabel: "Aug 01, 15:20 - 16:00",
      aiSummary: "response-time increase supports connection saturation as the root cause",
      metricSeries: [
        { time: "15:00", value: 28 },
        { time: "15:10", value: 32 },
        { time: "15:20", value: 58 },
        { time: "15:24", value: 142 },
        { time: "15:30", value: 96 },
        { time: "15:45", value: 44 },
        { time: "16:00", value: 36 },
      ],
      related: [
        { id: "ev-1", title: "Database Connection Errors Spiked", type: "Metric", relevance: "98%" },
        { id: "ev-5", title: "Slow Query Trace", type: "Trace", relevance: "90%" },
      ],
    },
    {
      id: "ev-4",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:22:41",
      ago: "6 mins ago",
      title: "Connection pool utilization",
      type: "Metric",
      relevance: "88%",
      source: "Prometheus",
      component: "postgresql-primary",
      sparkline: [40, 44, 48, 52, 60, 72, 88, 96, 99, 99, 97, 94],
      sparklineColor: "red",
      description: "Pool utilization reached the configured max of 100 connections.",
      windowLabel: "Aug 01, 15:15 - 16:00",
      aiSummary: "pool saturation is the strongest leading indicator for this incident",
      metricSeries: [
        { time: "15:00", value: 42 },
        { time: "15:10", value: 55 },
        { time: "15:20", value: 91 },
        { time: "15:25", value: 99 },
        { time: "15:40", value: 86 },
        { time: "16:00", value: 61 },
      ],
      related: [
        { id: "ev-7", title: "Connection Pool Exhausted", type: "Log", relevance: "80%" },
        { id: "ev-1", title: "Database Connection Errors Spiked", type: "Metric", relevance: "98%" },
      ],
    },
    {
      id: "ev-6",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:21:18",
      ago: "7 mins ago",
      title: "Ingress 5xx rate above SLO",
      type: "Metric",
      relevance: "76%",
      source: "Prometheus",
      component: "nginx-ingress",
      sparkline: [10, 12, 11, 14, 18, 22, 40, 55, 48, 36, 28, 22],
      sparklineColor: "orange",
      description: "Edge 5xx burst follows database connection failures on payment paths.",
      windowLabel: "Aug 01, 15:10 - 16:00",
      aiSummary: "ingress errors are a downstream symptom, not the originating cause",
      metricSeries: [
        { time: "15:00", value: 8 },
        { time: "15:15", value: 14 },
        { time: "15:24", value: 46 },
        { time: "15:40", value: 22 },
        { time: "16:00", value: 11 },
      ],
      related: [
        { id: "ev-8", title: "POST /checkout 504 Timeout", type: "Trace", relevance: "84%" },
        { id: "ev-2", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%" },
      ],
    },
    {
      id: "ev-11",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:19:02",
      ago: "9 mins ago",
      title: "Disk wait spike on primary",
      type: "Metric",
      relevance: "71%",
      source: "Prometheus",
      component: "postgresql-primary",
      sparkline: [18, 20, 22, 28, 40, 62, 58, 44, 30, 24],
      sparklineColor: "orange",
      description: "Storage wait increased as connection backlog accumulated.",
      windowLabel: "Aug 01, 15:10 - 16:00",
      aiSummary: "disk wait is correlated but weaker than connection-pool evidence",
      metricSeries: [
        { time: "15:00", value: 18 },
        { time: "15:20", value: 64 },
        { time: "15:30", value: 41 },
        { time: "16:00", value: 22 },
      ],
      related: [
        { id: "ev-1", title: "Database Connection Errors Spiked", type: "Metric", relevance: "98%" },
      ],
    },
    {
      id: "ev-7",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:23:12",
      ago: "5 mins ago",
      title: "Connection Pool Exhausted",
      type: "Log",
      relevance: "80%",
      source: "app-logs",
      component: "pymt-svc",
      description: "Clients were rejected after the pool hit its maximum size.",
      windowLabel: "Aug 01, 13:25 - 14:00",
      aiSummary: "log pattern matches pool exhaustion as a contributing signal",
      logSamples: [
        { time: "2026-08-01 13:25:51", level: "ERROR", service: "payment-svc", message: "HikariPool: connection is not available, request timed out after 30000ms" },
        { time: "2026-08-01 13:25:54", level: "WARN", service: "payment-svc", message: "Active connections=100 idle=0 waiting=24" },
        { time: "2026-08-01 13:26:08", level: "ERROR", service: "payment-svc", message: "Rejecting checkout request: pool exhausted" },
      ],
      patterns: timeoutPatterns.slice(1),
      rawData: "[2026-08-01 13:25:51] ERROR payment-svc: HikariPool: connection is not available\n[2026-08-01 13:25:54] WARN  payment-svc: Active connections=100 idle=0 waiting=24",
      affectedServices: [
        { name: "payment-svc", impact: "Request rejection" },
        { name: "checkout-svc", impact: "Retry amplification" },
      ],
      related: [
        { id: "ev-2", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%" },
        { id: "ev-4", title: "Connection pool utilization", type: "Metric", relevance: "88%" },
      ],
    },
    {
      id: "ev-9",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:22:04",
      ago: "6 mins ago",
      title: "Retry connection failures",
      type: "Log",
      relevance: "78%",
      source: "app-logs",
      component: "pymt-svc",
      description: "Retry storms followed the first wave of timeout errors.",
      windowLabel: "Aug 01, 13:25 - 14:00",
      aiSummary: "retries amplified load on an already saturated pool",
      logSamples: [
        { time: "2026-08-01 13:25:48", level: "WARN", service: "payment-svc", message: "Retrying database connection (attempt 3/5)" },
        { time: "2026-08-01 13:25:50", level: "ERROR", service: "payment-svc", message: "All retry attempts to connect failed" },
      ],
      patterns: [timeoutPatterns[2]],
      rawData: "[2026-08-01 13:25:50] ERROR payment-svc: All retry attempts to connect failed",
      affectedServices: [{ name: "payment-svc", impact: "Retry amplification" }],
      related: [
        { id: "ev-2", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%" },
      ],
    },
    {
      id: "ev-10",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:18:44",
      ago: "10 mins ago",
      title: "Slow query log burst",
      type: "Log",
      relevance: "69%",
      source: "app-logs",
      component: "postgresql-primary",
      description: "Slow queries clustered around the connection-error window.",
      windowLabel: "Aug 01, 13:20 - 14:00",
      aiSummary: "slow queries are consistent with lock wait under connection pressure",
      logSamples: [
        { time: "2026-08-01 13:24:11", level: "WARN", service: "postgresql", message: "duration: 4821.312 ms  statement: SELECT * FROM payments WHERE status='open'" },
      ],
      patterns: [timeoutPatterns[3]],
      rawData: "duration: 4821.312 ms  statement: SELECT * FROM payments WHERE status='open'",
      affectedServices: [{ name: "postgresql-primary", impact: "Lock wait" }],
      related: [
        { id: "ev-5", title: "Slow Query Trace", type: "Trace", relevance: "90%" },
      ],
    },
    {
      id: "ev-5",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:23:40",
      ago: "5 mins ago",
      title: "Slow Query Trace",
      type: "Trace",
      relevance: "90%",
      source: "OpenTelemetry",
      component: "postgresql-primary",
      description: "Checkout traces stall on the postgresql-primary span.",
      windowLabel: "Aug 01, 15:20 - 16:00",
      aiSummary: "trace latency is concentrated in the database span, matching RCA",
      related: [
        { id: "ev-1", title: "Database Connection Errors Spiked", type: "Metric", relevance: "98%" },
        { id: "ev-2", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%" },
      ],
    },
    {
      id: "ev-8",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:20:16",
      ago: "8 mins ago",
      title: "POST /checkout 504 Timeout",
      type: "Trace",
      relevance: "84%",
      source: "OpenTelemetry",
      component: "checkout-svc",
      description: "Checkout requests time out waiting on payment-svc database calls.",
      windowLabel: "Aug 01, 15:15 - 16:00",
      aiSummary: "504s are a user-facing symptom of the database connection failure",
      related: [
        { id: "ev-6", title: "Ingress 5xx rate above SLO", type: "Metric", relevance: "76%" },
        { id: "ev-2", title: "PostgreSQL Connection Timeout Errors", type: "Log", relevance: "95%" },
      ],
    },
    {
      id: "ev-12",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      time: "15:17:55",
      ago: "11 mins ago",
      title: "payment-svc to postgresql span",
      type: "Trace",
      relevance: "73%",
      source: "OpenTelemetry",
      component: "pymt-svc",
      description: "Downstream spans show repeated connection acquire timeouts.",
      windowLabel: "Aug 01, 15:10 - 16:00",
      aiSummary: "span errors corroborate pool acquire timeouts on pymt-svc",
      related: [
        { id: "ev-5", title: "Slow Query Trace", type: "Trace", relevance: "90%" },
        { id: "ev-4", title: "Connection pool utilization", type: "Metric", relevance: "88%" },
      ],
    },
  ],
};

export const mockRemediation: RemediationPage = {
  highlights: [
    { title: "Open Actions", value: "3", description: "Need review", tone: "warning" },
    { title: "Applied Today", value: "1", description: "Rollback cache TTL", tone: "ok" },
    { title: "Manual Only", value: "2", description: "Requires approval", tone: "critical" },
    { title: "Avg Confidence", value: "86%", description: "AI ranked", tone: "neutral" },
  ],
  items: [
    {
      id: "act-increase-pool",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      title: "Increase connection pool size",
      description:
        "Increase PostgreSQL connection pool size to 100 or rollback to previous configuration.",
      expectedImpact: "Restore connections and reduce timeout errors",
      confidence: "High (91%)",
      riskLevel: "Medium",
      status: "Recommended",
      manualOnly: true,
      updatedAgo: "2 mins ago",
    },
    {
      id: "act-scale-payment",
      incidentId: MOCK_INCIDENT_ID,
      incidentCode: "INC-4082",
      title: "Scale payment service replicas",
      description: "Temporarily scale pymt-svc from 12 to 18 replicas while pool recovery completes.",
      expectedImpact: "Absorb retry backlog without cascading timeouts",
      confidence: "Medium (74%)",
      riskLevel: "Low",
      status: "In Progress",
      manualOnly: false,
      updatedAgo: "6 mins ago",
    },
    {
      id: "act-rollback-ttl",
      incidentId: "inc-4071",
      incidentCode: "INC-4071",
      title: "Rollback cache TTL change",
      description: "Revert redis-cache TTL from 30s to 5m to stop stampede on origin.",
      expectedImpact: "Normalize origin QPS and checkout latency",
      confidence: "High (88%)",
      riskLevel: "Low",
      status: "Applied",
      manualOnly: false,
      updatedAgo: "18 mins ago",
    },
    {
      id: "act-circuit-breaker",
      incidentId: "inc-4071",
      incidentCode: "INC-4071",
      title: "Enable checkout circuit breaker",
      description: "Open breaker on POST /checkout when 5xx exceeds 8% for 60s.",
      expectedImpact: "Protect downstream payment pods",
      confidence: "Medium (69%)",
      riskLevel: "Medium",
      status: "Failed",
      manualOnly: true,
      updatedAgo: "41 mins ago",
    },
  ],
};
